# Generated by Django 3.2 on 2021-04-13 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mahjong.models.groupmodel


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0002_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=mahjong.models.groupmodel.upload_group_path),
        ),
        migrations.AlterField(
            model_name='gameresults',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('group_id', 'user_id')},
        ),
    ]
