# Generated by Django 3.2 on 2021-04-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0003_auto_20210413_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
