# Generated by Django 3.2 on 2021-04-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0005_alter_rate_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
